#!/usr/bin/env python3
"""Bulk-generate exam questions using the existing AI Edge Function.

This reuses the same Supabase Edge Function the app already uses:
  POST /functions/v1/generate-questions

Flow:
1) Call the Edge Function in small batches to generate questions.
2) Normalize shape to match the CSV importer (exactly 3 wrong answers, etc.).
3) Validate with validate_import.py (includes semantic checks like Solve-for-x).
4) Insert into `exam_questions` via upload_and_insert.py (skip images upload).

Requires env vars:
- SUPABASE_URL
- SUPABASE_SERVICE_ROLE_KEY

Notes:
- Diagrams generated by the Edge Function are already uploaded by the function
  and returned as a URL in image_url. We keep those and insert as-is.
- The validator is the safety net: if AI produces inconsistent questions, the run fails.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
import uuid
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Tuple

import re


DB_TOPICS = [
    "Number",
    "Algebra",
    "Ratio & Proportion",
    "Geometry & Measures",
    "Probability",
    "Statistics",
]

# Edge Function expects "Geometry" but app/DB uses "Geometry & Measures".
EDGE_TOPIC_BY_DB_TOPIC: Dict[str, str] = {
    "Number": "Number",
    "Algebra": "Algebra",
    "Ratio & Proportion": "Ratio & Proportion",
    "Geometry & Measures": "Geometry",
    "Probability": "Probability",
    "Statistics": "Statistics",
}


def _env(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        raise SystemExit(f"Missing required env var: {name}")
    return v


def _http_json(method: str, url: str, headers: Dict[str, str], payload: Any | None, timeout: int = 90) -> Tuple[int, str]:
    data = None
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        headers = {**headers, "Content-Type": "application/json"}
        data = body
    req = urllib.request.Request(url=url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", errors="replace")


def _dedupe_preserve(items: List[str]) -> List[str]:
    seen = set()
    out: List[str] = []
    for x in items:
        x = str(x).strip()
        if not x or x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


_RE_NUMBER = re.compile(r"(?<![a-zA-Z])[-+]?\d+(?:\.\d+)?(?:/\d+(?:\.\d+)?)?(?![a-zA-Z])")
_RE_CURRENCY = re.compile(r"[£$€]\s*\d+(?:,\d{3})*(?:\.\d+)?")
_RE_PERCENT = re.compile(r"\b\d+(?:\.\d+)?\s*%\b")
_RE_TIME = re.compile(r"\b\d+(?:\.\d+)?\s*(?:s|sec|secs|second|seconds|min|mins|minute|minutes|h|hr|hrs|hour|hours)\b", re.I)
_RE_UNIT = re.compile(
    r"\b\d+(?:\.\d+)?\s*(?:cm|mm|m|km|g|kg|ml|l|litre|litres|mile|miles|mph|km/h|m/s|°)\b",
    re.I,
)


def question_style_signature(topic: str, tier: str, text: str) -> str:
    """Create a template-like signature so 'same question with different numbers' de-dupes.

    Example: 'A car travels 240 miles in 6 hours...' and 'A car travels 180 miles in 3 hours...'
    should map to the same signature.
    """
    s = " ".join((text or "").split()).lower()

    # Normalize some common latex wrappers that might vary.
    s = s.replace("\\\\[", "").replace("\\\\]", "").replace("\\[", "").replace("\\]", "")
    s = s.replace("\\\\(", "").replace("\\\\)", "").replace("\\(", "").replace("\\)", "")

    # Replace currency/percent/units/time with placeholders before generic number stripping.
    s = _RE_CURRENCY.sub("<CURRENCY>", s)
    s = _RE_PERCENT.sub("<PERCENT>", s)
    s = _RE_TIME.sub("<TIME>", s)
    s = _RE_UNIT.sub("<UNIT>", s)

    # Replace remaining numeric literals (integers/decimals/fractions) with a placeholder.
    s = _RE_NUMBER.sub("<N>", s)

    # Collapse repeated placeholders.
    s = re.sub(r"(<n>\s*){2,}", "<n> ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return f"{topic}|{tier}|{s}"


def ensure_three_wrong_answers(correct: str, wrong: List[str]) -> List[str]:
    correct = str(correct).strip()
    wrong = _dedupe_preserve([str(w) for w in (wrong or [])])
    wrong = [w for w in wrong if w != correct]

    # Trim extras.
    if len(wrong) > 3:
        wrong = wrong[:3]

    # Top up if too few.
    # Use small textual variants to avoid infinite loops.
    attempts = 0
    while len(wrong) < 3 and attempts < 50:
        attempts += 1
        candidate = None
        # If numeric-ish, add +/- offsets.
        try:
            base = float(correct)
            delta = [1, -1, 2, -2, 3, -3, 0.5, -0.5][attempts % 8]
            v = base + delta
            # preserve int look if correct looks like int
            if correct.lstrip("-").isdigit() and abs(v - round(v)) < 1e-9:
                candidate = str(int(round(v)))
            else:
                candidate = str(v).rstrip("0").rstrip(".")
        except Exception:
            candidate = str(attempts)

        if candidate and candidate != correct and candidate not in wrong:
            wrong.append(candidate)

    return wrong[:3]


def normalize_calculator(calc: str) -> str:
    c = (calc or "").strip().lower()
    if c in ("calculator", "calc"):
        return "Calculator"
    return "Non-Calculator"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Bulk-generate questions using AI Edge Function")
    p.add_argument("--tier", choices=["foundation", "higher"], required=True)
    p.add_argument("--count", type=int, default=100)
    p.add_argument("--topics", default="all", help="Comma-separated topics, or 'all'")
    p.add_argument("--calculator-type", choices=["both", "calculator", "non-calculator"], default="both")
    p.add_argument("--force-images", action="store_true", help="Force diagrams (slower/costlier)")
    p.add_argument("--batch-size", type=int, default=10, help="How many to ask AI for per request")
    p.add_argument(
        "--no-dedupe",
        action="store_true",
        help="Disable de-duplication of generated question stems",
    )
    p.add_argument(
        "--max-requests-per-topic",
        type=int,
        default=200,
        help="Safety cap to avoid infinite loops when de-duping",
    )
    p.add_argument("--out-dir", default=str(Path("supabase") / "data" / "generated"))
    p.add_argument("--batch-id", default=None)
    p.add_argument("--push", action="store_true", help="Insert into Supabase after generating")
    p.add_argument("--chunk-size", type=int, default=200)
    return p.parse_args()


def tier_to_db(t: str) -> str:
    return "Higher Tier" if t == "higher" else "Foundation Tier"


def pick_defaults_for_meta(db_tier: str) -> Tuple[int, int, int]:
    # marks, difficulty, estimated_time_sec
    if db_tier == "Higher Tier":
        return 1, 4, 105
    return 1, 2, 75


def call_generate_questions(*, supabase_url: str, service_key: str, topic: str, tier: str, count: int, calculator_type: str, force_images: bool) -> List[Dict[str, Any]]:
    url = f"{supabase_url.rstrip('/')}/functions/v1/generate-questions"
    headers = {
        "apikey": service_key,
        "Authorization": f"Bearer {service_key}",
    }
    payload = {
        "action": "generate",
        "topic": topic,
        "tier": tier,
        "count": int(count),
        "calculatorType": calculator_type,
        "forceImages": bool(force_images),
    }
    # Retry transient failures. Also, if the function struggles with larger counts,
    # the caller may reduce count and retry.
    last_err: str | None = None
    for attempt in range(1, 6):
        status, body = _http_json("POST", url, headers, payload, timeout=180)
        if status in (200, 201):
            data = json.loads(body or "{}")
            if isinstance(data, dict) and data.get("error"):
                last_err = str(data.get("error"))
            else:
                questions = data.get("questions") if isinstance(data, dict) else None
                if isinstance(questions, list):
                    return questions
                last_err = "Missing questions array in response"
        else:
            last_err = f"status={status} body={body[:500]}"

        # backoff
        time.sleep(0.35 * attempt)

    raise SystemExit(f"Edge function generate-questions failed after retries: {last_err}")


def write_csv(rows: List[Dict[str, Any]], csv_path: Path) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "id",
                "question_type",
                "tier",
                "calculator",
                "subtopic",
                "question",
                "correct_answer",
                "wrong_answers",
                "marks",
                "difficulty",
                "estimated_time_sec",
                "image_url",
                "image_alt",
                "explanation",
            ],
        )
        w.writeheader()
        for r in rows:
            w.writerow(r)


def main() -> None:
    args = parse_args()

    supabase_url = _env("SUPABASE_URL")
    service_key = _env("SUPABASE_SERVICE_ROLE_KEY")

    topics = DB_TOPICS if args.topics.strip().lower() == "all" else [t.strip() for t in args.topics.split(",") if t.strip()]
    unknown = [t for t in topics if t not in DB_TOPICS]
    if unknown:
        raise SystemExit(f"Unknown topics: {unknown}. Allowed: {DB_TOPICS}")

    db_tier = tier_to_db(args.tier)

    if args.batch_id:
        batch_id = args.batch_id
    else:
        batch_id = f"ai_{time.strftime('%Y%m%d_%H%M%S')}"

    batch_root = Path(args.out_dir) / f"batch_{batch_id}"
    csv_path = batch_root / "exam_questions.csv"

    total = int(args.count)
    batch_size = max(1, min(int(args.batch_size), 25))

    print("AI generation:")
    print("  tier:", db_tier)
    print("  topics:", topics)
    print("  total:", total)
    print("  batch_size:", batch_size)
    print("  output:", csv_path)

    # Evenly distribute across topics for now.
    per_topic_base = total // len(topics)
    remainder = total % len(topics)
    per_topic = {t: per_topic_base + (1 if i < remainder else 0) for i, t in enumerate(topics)}

    out_rows: List[Dict[str, Any]] = []
    dedupe = not args.no_dedupe
    seen_stems: set[str] = set()

    for topic in topics:
        need = per_topic[topic]
        if need <= 0:
            continue
        print(f"\nTopic: {topic} -> generating {need}")

        generated = 0
        reqs = 0
        while generated < need:
            reqs += 1
            if dedupe and reqs > int(args.max_requests_per_topic):
                raise SystemExit(
                    f"Exceeded max requests for topic '{topic}'. "
                    "Try increasing --max-requests-per-topic or disabling --no-dedupe."
                )
            n = min(batch_size, need - generated)
            edge_topic = EDGE_TOPIC_BY_DB_TOPIC.get(topic)
            if not edge_topic:
                raise SystemExit(f"No edge-topic mapping for DB topic: {topic}")
            qs = call_generate_questions(
                supabase_url=supabase_url,
                service_key=service_key,
                topic=edge_topic,
                tier=db_tier,
                count=n,
                calculator_type=args.calculator_type,
                force_images=args.force_images,
            )

            if not qs:
                raise SystemExit("AI returned no questions; aborting")

            accepted_this_round = 0
            for q in qs:
                q_text = str(q.get("question") or "").strip()
                correct = str(q.get("correct_answer") or "").strip()
                wrong = ensure_three_wrong_answers(correct, q.get("wrong_answers") or [])

                # De-dupe by normalized stem
                if dedupe:
                    # De-dupe by style (template), not just by exact numbers.
                    sig = question_style_signature(topic, db_tier, q_text)
                    if sig in seen_stems:
                        continue
                    seen_stems.add(sig)

                marks, difficulty, estimated = pick_defaults_for_meta(db_tier)
                subtopic = str(q.get("question_type") or "").strip()

                out_rows.append(
                    {
                        "id": str(uuid.uuid4()),
                        "question_type": topic,
                        "tier": db_tier,
                        "calculator": normalize_calculator(str(q.get("calculator") or "")),
                        "subtopic": subtopic,
                        "question": q_text,
                        "correct_answer": correct,
                        "wrong_answers": json.dumps(wrong, ensure_ascii=False),
                        "marks": str(marks),
                        "difficulty": str(difficulty),
                        "estimated_time_sec": str(estimated),
                        "image_url": str(q.get("image_url") or "").strip() or "",
                        "image_alt": str(q.get("image_alt") or q.get("diagram_description") or "").strip() or "",
                        "explanation": str(q.get("explanation") or "").strip(),
                    }
                )

                generated += 1
                accepted_this_round += 1
                if generated >= need:
                    break

            print(f"  generated {generated}/{need} (+{accepted_this_round} accepted)")
            time.sleep(0.15)

    write_csv(out_rows, csv_path)

    # Validate using the repo validator.
    from validate_import import validate_row  # type: ignore

    errs = 0
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, start=2):
            row_errors = validate_row(row, i)
            if row_errors:
                errs += 1
                print(f"Row {i} errors:")
                for e in row_errors:
                    print("  -", e)

    if errs:
        raise SystemExit(f"Validation failed: {errs} row(s) with errors")

    print("\nValidation passed  - CSV looks good.")

    if not args.push:
        print("\nNot pushing (use --push to insert into Supabase)")
        return

    # Insert via existing importer (skip image uploads because image_url points to already-hosted URLs)
    from upload_and_insert import insert_rows, read_csv_rows  # type: ignore

    rows = read_csv_rows(Path(csv_path))
    insert_rows(
        supabase_url=supabase_url,
        service_key=service_key,
        rows=rows,
        upsert=True,
        chunk_size=int(args.chunk_size),
    )

    print("\nPush complete.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted", file=sys.stderr)
        sys.exit(130)
