import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { 
  ArrowLeft, 
  Play, 
  CheckCircle, 
  Target,
  Clock,
  Award,
  BookOpen
} from "lucide-react";
import { toast } from "sonner";
import { useAppContext } from '@/hooks/useAppContext';
import MathText from "@/components/MathText";

interface Question {
  id: number;
  question: string;
  marks: number;
  subtopic_key: string;
  topic_key: string;
}

interface Answer {
  questionId: number;
  answer: string;
  marks?: number;
  feedback?: string;
}

interface SubtopicOption {
  key: string;
  label: string;
  topic_key: string;
  subtopic_key: string;
  score: number;
}

const TOPIC_NAMES: Record<string, string> = {
  number: 'Number',
  algebra: 'Algebra', 
  ratio: 'Ratio & Proportion',
  geometry: 'Geometry & Measures',
  probability: 'Probability',
  statistics: 'Statistics'
};

// Mock questions for demo - in real app these would be generated by AI
const MOCK_QUESTIONS: Question[] = [
  {
    id: 1,
    question: "Factorise completely: $x^2 + 7x + 12$",
    marks: 2,
    subtopic_key: "quadratic_formula",
    topic_key: "algebra"
  },
  {
    id: 2,
    question: "Calculate the area of a circle with radius 5cm. Give your answer to 2 decimal places.",
    marks: 3,
    subtopic_key: "perimeter_area_volume",
    topic_key: "geometry"
  },
  {
    id: 3,
    question: "A bag contains 3 red balls and 7 blue balls. What is the probability of picking a red ball?",
    marks: 2,
    subtopic_key: "basic_probability",
    topic_key: "probability"
  },
  {
    id: 4,
    question: "Simplify: $\\frac{2}{3} + \\frac{1}{4}$",
    marks: 2,
    subtopic_key: "fractions_decimals_percentages",
    topic_key: "number"
  },
  {
    id: 5,
    question: "The mean of 5 numbers is 8. Four of the numbers are 6, 7, 9, and 11. What is the fifth number?",
    marks: 3,
    subtopic_key: "measures_central_tendency",
    topic_key: "statistics"
  }
];

export function MiniMock() {
  const { user } = useAppContext();
  const navigate = useNavigate();
  const [selectedSubtopics, setSelectedSubtopics] = useState<string[]>([]);
  const [subtopicOptions, setSubtopicOptions] = useState<SubtopicOption[]>([]);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [timeRemaining, setTimeRemaining] = useState(15 * 60); // 15 minutes
  const [mockStarted, setMockStarted] = useState(false);
  const [mockCompleted, setMockCompleted] = useState(false);
  const [totalMarks, setTotalMarks] = useState(0);
  const [earnedMarks, setEarnedMarks] = useState(0);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // TODO: Fetch subtopic options from database
    // For now, using mock data
    const mockOptions: SubtopicOption[] = [
      { key: "algebra.quadratic_formula", label: "Algebra → Quadratic Formula", topic_key: "algebra", subtopic_key: "quadratic_formula", score: 45 },
      { key: "geometry.perimeter_area_volume", label: "Geometry → Area & Volume", topic_key: "geometry", subtopic_key: "perimeter_area_volume", score: 30 },
      { key: "probability.basic_probability", label: "Probability → Basic Probability", topic_key: "probability", subtopic_key: "basic_probability", score: 20 },
      { key: "number.fractions_decimals_percentages", label: "Number → Fractions & Decimals", topic_key: "number", subtopic_key: "fractions_decimals_percentages", score: 50 },
      { key: "statistics.measures_central_tendency", label: "Statistics → Mean, Median, Mode", topic_key: "statistics", subtopic_key: "measures_central_tendency", score: 35 }
    ];
    
    // Auto-select weakest subtopics
    const weakest = [...mockOptions]
      .sort((a, b) => a.score - b.score)
      .slice(0, 5)
      .map(opt => opt.key);
    
    setSubtopicOptions(mockOptions);
    setSelectedSubtopics(weakest);
  }, []);

  const formatTime = (seconds: number) => {
    const totalSeconds = Math.max(0, Math.floor(seconds));
    const hrs = Math.floor(totalSeconds / 3600);
    const mins = Math.floor((totalSeconds % 3600) / 60);
    const secs = totalSeconds % 60;
    if (hrs > 0) {
      return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handleStartMock = useCallback(() => {
    if (selectedSubtopics.length === 0) {
      toast.error('Please select at least one subtopic');
      return;
    }

    // For demo, use mock questions
    // TODO: Generate questions via AI based on selected subtopics
    setQuestions(MOCK_QUESTIONS);
    setAnswers(MOCK_QUESTIONS.map(q => ({ questionId: q.id, answer: '' })));
    setTotalMarks(MOCK_QUESTIONS.reduce((sum, q) => sum + q.marks, 0));
    setMockStarted(true);
    setCurrentQuestion(0);
    setTimeRemaining(15 * 60);
  }, [selectedSubtopics]);

  const handleAnswerChange = (questionId: number, answer: string) => {
    setAnswers(prev => prev.map(a => 
      a.questionId === questionId ? { ...a, answer } : a
    ));
  };

  const handleSubmitMock = useCallback(async () => {
    if (mockCompleted) return;
    
    setLoading(true);
    setMockCompleted(true);

    try {
      // TODO: Call AI to mark answers and provide feedback
      // For demo, simulate marking
      let totalEarned = 0;
      const markedAnswers = answers.map(answer => {
        const question = questions.find(q => q.id === answer.questionId);
        if (!question) return answer;

        // Mock marking logic
        const marks = Math.floor(Math.random() * (question.marks + 1));
        totalEarned += marks;
        
        return {
          ...answer,
          marks,
          feedback: marks === question.marks ? 'Excellent!' : marks > 0 ? 'Partial credit - good attempt' : 'Needs improvement'
        };
      });

      setAnswers(markedAnswers);
      setEarnedMarks(totalEarned);

      // TODO: Update subtopic progress based on performance
      const percentage = totalMarks > 0 ? (totalEarned / totalMarks) * 100 : 0;
      const increment = percentage >= 80 ? 5 : percentage >= 50 ? 3 : 1;

      toast.success(`Mock completed! Score: ${totalEarned}/${totalMarks} (${Math.round(percentage)}%)`);
    } catch (error) {
      console.error('Error submitting mock:', error);
      toast.error('Failed to submit mock exam');
    } finally {
      setLoading(false);
    }
  }, [answers, mockCompleted, questions, totalMarks]);

  useEffect(() => {
    if (!mockStarted || mockCompleted) return;

    const timer = setInterval(() => {
      setTimeRemaining(prev => {
        if (prev <= 1) {
          void handleSubmitMock();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [mockStarted, mockCompleted, handleSubmitMock]);

  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  if (mockCompleted) {
    const percentage = totalMarks > 0 ? Math.round((earnedMarks / totalMarks) * 100) : 0;
    
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={() => navigate('/readiness')}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Readiness
          </Button>
        </div>

        <Card className="bg-gradient-card border-0 shadow-card">
          <CardHeader className="text-center">
            <CardTitle className="flex items-center justify-center gap-2 text-2xl">
              <Award className="h-6 w-6 text-warning" />
              Mini-Mock Results
            </CardTitle>
            <CardDescription>
              Your performance on 5 GCSE Mathematics questions
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Overall Score */}
            <div className="text-center space-y-4">
              <div className="text-4xl font-bold text-accent">
                {earnedMarks}/{totalMarks}
              </div>
              <div className="text-2xl font-semibold">
                {percentage}%
              </div>
              <Badge 
                className={`text-lg px-4 py-2 ${
                  percentage >= 80 ? 'bg-[#10b981] text-white' :
                  percentage >= 50 ? 'bg-[#f59e0b] text-white' :
                  'bg-[#ef4444] text-white'
                }`}
              >
                {percentage >= 80 ? 'Excellent' : percentage >= 50 ? 'Good Effort' : 'Needs Work'}
              </Badge>
            </div>

            {/* Question Breakdown */}
            <div className="space-y-4">
              <h3 className="font-semibold">Question Breakdown</h3>
              {questions.map((question, index) => {
                const answer = answers.find(a => a.questionId === question.id);
                return (
                  <div key={question.id} className="border rounded-lg p-4 space-y-2">
                    <div className="flex items-center justify-between">
                      <h4 className="font-medium">Question {index + 1}</h4>
                      <Badge variant="outline">
                        {answer?.marks || 0}/{question.marks} marks
                      </Badge>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <MathText text={question.question} display={true} />
                    </div>
                    {answer?.feedback && (
                      <p className="text-sm text-muted-foreground italic">
                        {answer.feedback}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>

            <div className="flex gap-2">
              <Button 
                onClick={() => navigate('/readiness')}
                className="flex-1"
              >
                <Target className="h-4 w-4 mr-2" />
                Review Weak Areas
              </Button>
              <Button 
                variant="outline"
                onClick={() => window.location.reload()}
                className="flex-1"
              >
                Try Again
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (mockStarted) {
    const question = questions[currentQuestion];
    const answer = answers.find(a => a.questionId === question?.id);
    const totalQuestions = questions.length;
    const questionNumber = totalQuestions > 0 ? currentQuestion + 1 : 0;
    const progressValue = totalQuestions > 0 ? (questionNumber / totalQuestions) * 100 : 0;
    
    return (
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" onClick={() => navigate('/readiness')}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <Badge variant="outline">
              Question {questionNumber} of {totalQuestions}
            </Badge>
          </div>
          <div className="flex items-center gap-2 text-lg font-semibold">
            <Clock className="h-5 w-5" />
            {formatTime(timeRemaining)}
          </div>
        </div>

        {/* Progress */}
        <div className="space-y-2">
          <div className="flex justify-between text-sm">
            <span>Progress</span>
            <span>{questionNumber}/{totalQuestions}</span>
          </div>
          <Progress value={progressValue} />
        </div>

        {/* Question */}
        <Card className="bg-gradient-card border-0 shadow-card">
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span>Question {questionNumber}</span>
              <Badge variant="secondary">{question?.marks} marks</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="text-lg">
              <MathText text={question?.question || ''} display={true} />
            </div>
            
            <Textarea
              placeholder="Enter your answer here..."
              value={answer?.answer || ''}
              onChange={(e) => handleAnswerChange(question?.id || 0, e.target.value)}
              className="min-h-[120px]"
            />
            
            <div className="flex justify-between">
              <Button 
                variant="outline"
                onClick={() => setCurrentQuestion(Math.max(0, currentQuestion - 1))}
                disabled={currentQuestion === 0}
              >
                Previous
              </Button>
              
              {currentQuestion === questions.length - 1 ? (
                <Button onClick={handleSubmitMock} disabled={loading}>
                  {loading ? 'Submitting...' : 'Submit Mock'}
                </Button>
              ) : (
                <Button 
                  onClick={() => setCurrentQuestion(Math.min(questions.length - 1, currentQuestion + 1))}
                >
                  Next
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Setup screen
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" onClick={() => navigate('/readiness')}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Readiness
        </Button>
      </div>

      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold flex items-center justify-center gap-3">
          <Play className="h-8 w-8 text-warning" />
          Mini-Mock (5 Questions)
        </h1>
        <p className="text-muted-foreground">
          Quick GCSE Mathematics practice exam
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Setup */}
        <Card className="bg-gradient-card border-0 shadow-card">
          <CardHeader>
            <CardTitle>Select Topics</CardTitle>
            <CardDescription>
              Choose up to 5 subtopics to focus on (weakest selected by default)
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3 max-h-64 overflow-y-auto">
              {subtopicOptions.map((option) => (
                <div key={option.key} className="flex items-center space-x-3">
                  <Checkbox
                    id={option.key}
                    checked={selectedSubtopics.includes(option.key)}
                    onCheckedChange={(checked) => {
                      setSelectedSubtopics(prev => {
                        if (checked) {
                          if (prev.length < 5) {
                            return [...prev, option.key];
                          }
                          toast.error('Maximum 5 subtopics allowed');
                          return prev;
                        }
                        return prev.filter(key => key !== option.key);
                      });
                    }}
                    disabled={!selectedSubtopics.includes(option.key) && selectedSubtopics.length >= 5}
                  />
                  <label htmlFor={option.key} className="text-sm flex-1">
                    {option.label}
                  </label>
                  <Badge 
                    className={`text-xs ${
                      option.score >= 70 ? 'bg-[#10b981] text-white' :
                      option.score >= 40 ? 'bg-[#f59e0b] text-white' :
                      'bg-[#ef4444] text-white'
                    }`}
                  >
                    {option.score}%
                  </Badge>
                </div>
              ))}
            </div>
            
            <Button 
              onClick={handleStartMock}
              disabled={selectedSubtopics.length === 0}
              className="w-full"
            >
              <Play className="h-4 w-4 mr-2" />
              Start Mini-Mock
            </Button>
          </CardContent>
        </Card>

        {/* Info */}
        <Card className="bg-gradient-card border-0 shadow-card">
          <CardHeader>
            <CardTitle>What to Expect</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <BookOpen className="h-4 w-4 text-accent" />
                <span className="text-sm">5 GCSE-style questions</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-accent" />
                <span className="text-sm">15 minutes time limit</span>
              </div>
              <div className="flex items-center gap-2">
                <Target className="h-4 w-4 text-accent" />
                <span className="text-sm">Instant feedback & marking</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-accent" />
                <span className="text-sm">Progress updates based on performance</span>
              </div>
            </div>
            
            <div className="border-t pt-4">
              <h4 className="font-medium mb-2">Scoring:</h4>
              <div className="text-sm space-y-1">
                <p>• 80%+ → +5 readiness points</p>
                <p>• 50-79% → +3 readiness points</p>
                <p>• Below 50% → +1 readiness point</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
