// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isAbortLikeError } from '@/lib/errors';

export const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) ?? "https://gknnfbalijxykqycopic.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrbm5mYmFsaWp4eWtxeWNvcGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzgxMzEsImV4cCI6MjA3MjIxNDEzMX0.nbJ6GgZmJ5ZPiTkYa_Y5C2G6Sep9IF8juXv4uU_CMDU";

const fetchWithRetry: typeof fetch = async (input, init) => {
  const maxRetries = 5;
  let attempt = 0;

  while (true) {
    try {
      return await fetch(input, init);
    } catch (error) {
      const externallyAborted = Boolean(init?.signal?.aborted);
      if (!isAbortLikeError(error) || externallyAborted || attempt >= maxRetries) {
        throw error;
      }
      attempt += 1;
      await new Promise((resolve) => setTimeout(resolve, 250 * attempt));
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithRetry,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }


});
