/**
 * Gradlify Mission Control — progress state
 * Updated by Cursor/Codex when milestones change.
 * Last updated: 2026-06-05
 */
window.GRADLIFY_PROGRESS = {
  meta: {
    lastUpdated: "2026-06-05",
    updatedBy: "Cursor",
    version: 1,
  },
  northStar: {
    mrr: 121,
    mrrTarget: 10000,
    payingCustomers: 6,
    payingTarget: 500,
    anchorEvent: "Live mock — 14 June 2026",
    anchorDate: "2026-06-14",
    deadlineMilestone: "2026-06-20",
  },
  rules: [
    "Parents buy proof (mock score), not apps.",
    "Partners say yes on a call — email only books the call.",
    "Do not contact Sutton 11 Plus.",
    "No paid Meta ads until trial→paid > 25%.",
  ],
  blocks: [
    {
      id: "block-1",
      number: 1,
      title: "Ship the funnel",
      subtitle: "Fix conversion before any big promotion",
      status: "active",
      owner: "mixed",
      why: "100 parents to a broken funnel wastes trust forever.",
      steps: [
        { id: "b1-1", title: "Production env VITE_APP_TRACK=11PLUS", status: "done", owner: "codex", when: "Before Block 2" },
        { id: "b1-2", title: "Live mock £10 everywhere (UI + Stripe)", status: "done", owner: "codex", when: "Before Block 2", note: "price_1Tf63lQYWoowhxMZKU2Z2AWY" },
        { id: "b1-3", title: "Start free practice CTA on landing", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-4", title: "Partner ?ref= banner on landing", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-5", title: "Post-mock parent report (score + weak topics)", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-6", title: "Honest copy: 1 mock/day (not 2)", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-7", title: "Deploy to production", status: "done", owner: "codex", when: "Before Block 2", note: "Commits 497af2b + 0e1895a" },
        { id: "b1-8", title: "30-min logged-in E2E test", status: "active", owner: "niketh", when: "Today", note: "New email → signup → mock → parent card → £10 checkout" },
      ],
    },
    {
      id: "block-2",
      number: 2,
      title: "Partner calls",
      subtitle: "Voice closes deals — email books the call",
      status: "pending",
      owner: "niketh",
      why: "Tutors trust your voice + demo, not a deck in email.",
      steps: [
        { id: "b2-1", title: "Book call — Chris (Eleven Plus Success)", status: "pending", owner: "niketh", when: "Today/tomorrow", contact: "tutor@elevenplussuccess.com · 07771740569", note: "Deck sent — goal: trial + 30% affiliate" },
        { id: "b2-2", title: "Book call — Andy (Pinner Road)", status: "pending", owner: "niketh", when: "Today/tomorrow", contact: "prlcharrow@gmail.com", note: "Deck sent — goal: 30% + ?ref=PRLC live" },
        { id: "b2-3", title: "Book call — David (11 Plus Hub)", status: "pending", owner: "niketh", when: "Today/tomorrow", contact: "info@11plushub.com", note: "Deck sent — affiliate on member site" },
        { id: "b2-4", title: "Book call — Mock Test Masters", status: "pending", owner: "niketh", when: "Today/tomorrow", contact: "info@mocktestmasters.com", note: "Deck sent — complement not compete" },
        { id: "b2-5", title: "Book call — Cecile (Frenchie Mummy)", status: "pending", owner: "niketh", when: "Today/tomorrow", contact: "cecile@thefrenchiemummy.com", note: "Deck sent — fix login on call" },
        { id: "b2-6", title: "Run 10-min call script on each", status: "pending", owner: "niketh", when: "This week" },
        { id: "b2-7", title: "Send ?ref= link + caption after each yes", status: "pending", owner: "niketh", when: "Within 1h of call" },
        { id: "b2-8", title: "Manual deck attach if they reply DECK", status: "pending", owner: "niketh", when: "As needed", note: "~/Downloads/Gradlify-Partner-Overview.pptx" },
      ],
    },
    {
      id: "block-3",
      number: 3,
      title: "Mock poster + assets",
      subtitle: "~1 hour — parents share images in WhatsApp",
      status: "pending",
      owner: "niketh",
      why: "GCs share posters more than bare links.",
      steps: [
        { id: "b3-1", title: "Poster 1080×1080 (Canva/Figma)", status: "pending", owner: "niketh", when: "After Block 2 started", note: "14 June mock · £10 / Premium free" },
        { id: "b3-2", title: "Story image 1080×1920", status: "pending", owner: "niketh", when: "Same session" },
        { id: "b3-3", title: "Save to outreach/assets/", status: "pending", owner: "niketh", when: "Same session" },
      ],
    },
    {
      id: "block-4",
      number: 4,
      title: "WhatsApp GCs",
      subtitle: "Highest trust — before Facebook",
      status: "pending",
      owner: "niketh",
      why: "Parents trust people they know in groups.",
      steps: [
        { id: "b4-1", title: "Message 5 paying subscribers (1:1)", status: "pending", owner: "niketh", when: "After poster ready" },
        { id: "b4-2", title: "Post poster in every GC you're in", status: "pending", owner: "niketh", when: "After poster ready" },
        { id: "b4-3", title: "Get 3 forwards into new GCs", status: "pending", owner: "niketh", when: "Ongoing" },
      ],
    },
    {
      id: "block-5",
      number: 5,
      title: "Facebook groups",
      subtitle: "Strangers — post feels like help, not ad",
      status: "pending",
      owner: "niketh",
      why: "Only works after Block 1 E2E passes.",
      steps: [
        { id: "b5-1", title: "Join 7 FB groups (request membership)", status: "pending", owner: "niketh", when: "This week" },
        { id: "b5-2", title: "Comment helpfully on 2 threads per group", status: "pending", owner: "niketh", when: "While waiting approval" },
        { id: "b5-3", title: "First helpful post per group", status: "pending", owner: "niketh", when: "After approved" },
        { id: "b5-4", title: "Reminder post ~7 June", status: "pending", owner: "niketh", when: "2026-06-07" },
      ],
    },
    {
      id: "block-6",
      number: 6,
      title: "14 June mock day",
      subtitle: "Score moment = when parents pay",
      status: "pending",
      owner: "niketh",
      why: "Follow up within 24h or you lose them.",
      steps: [
        { id: "b6-1", title: "13 June — GC reminder + tech test", status: "pending", owner: "niketh", when: "2026-06-13" },
        { id: "b6-2", title: "14 June — run mock + attendee sheet", status: "pending", owner: "niketh", when: "2026-06-14" },
        { id: "b6-3", title: "Within 24h — 1:1 message every attendee", status: "pending", owner: "niketh", when: "2026-06-15" },
        { id: "b6-4", title: "By 20 June — 3 new £19.99/mo subs", status: "pending", owner: "niketh", when: "2026-06-20" },
      ],
    },
    {
      id: "block-7",
      number: 7,
      title: "Daily rhythm",
      subtitle: "After Blocks 1–4 are moving",
      status: "pending",
      owner: "niketh",
      why: "Consistent execution beats sporadic bursts.",
      steps: [
        { id: "b7-1", title: "90 min — product / funnel fixes", status: "pending", owner: "niketh", when: "Daily AM" },
        { id: "b7-2", title: "60 min — 1 partner call or booking", status: "pending", owner: "niketh", when: "Daily" },
        { id: "b7-3", title: "60 min — 1 GC or FB post", status: "pending", owner: "niketh", when: "Daily" },
        { id: "b7-4", title: "45 min — follow up trials + mock leads", status: "pending", owner: "niketh", when: "Daily" },
        { id: "b7-5", title: "45 min — 1 short video", status: "pending", owner: "niketh", when: "Daily" },
        { id: "b7-6", title: "30 min — tracker + inbox", status: "pending", owner: "niketh", when: "Daily PM" },
      ],
    },
  ],
  milestones: [
    { id: "m1", label: "Block 1 deployed", date: "2026-06-05", status: "done" },
    { id: "m2", label: "Block 1 E2E tested", date: "2026-06-06", status: "active" },
    { id: "m3", label: "5 partner calls booked", date: "2026-06-08", status: "pending" },
    { id: "m4", label: "2 partners live with ?ref=", date: "2026-06-12", status: "pending" },
    { id: "m5", label: "FB reminder posts", date: "2026-06-07", status: "pending" },
    { id: "m6", label: "Live mock day", date: "2026-06-14", status: "pending" },
    { id: "m7", label: "3 new subs from mock", date: "2026-06-20", status: "pending" },
  ],
  successBy20June: [
    { id: "s1", label: "Block 1 shipped and tested", done: false },
    { id: "s2", label: "5 partner calls done (or 3+ completed)", done: false },
    { id: "s3", label: "2 partners live with ?ref= links", done: false },
    { id: "s4", label: "Poster in 3+ GCs + 5+ FB groups", done: false },
    { id: "s5", label: "20 families sit 14 June mock", done: false },
    { id: "s6", label: "3 new paid subs within 6 days of mock", done: false },
  ],
  doNotYet: [
    "Mass DM to Mathsaurus / big YouTubers",
    "Paid Meta ads",
    "Long email negotiations (book the call)",
    "Sutton 11 Plus",
    "FB posts before Block 1 E2E passes",
  ],
};
