/**
 * Gradlify Mission Control - progress state
 * Updated by Cursor when milestones change.
 * Last updated: 2026-06-07
 */
window.GRADLIFY_PROGRESS = {
  meta: {
    lastUpdated: "2026-06-07",
    updatedBy: "Cursor · £1k sprint · sent-ledger + audit-driven ops",
    version: 10,
  },
  pipeline: {
    block2: {
      stepsDone: 4,
      stepsTotal: 13,
      automatableDone: true,
      outcomePct: 35,
      tierA: { contacted: 5, total: 5, chased: 1, awaitingReply: 3, onHold: 1 },
      calls: { booked: 0, completed: 0, target: 5 },
      partnersLive: { count: 0, target: 2 },
      wave1Cold: { sent: 7, sentTo: ["Geek School", "Kin Learning", "Mathsaurus", "Top Dog", "Lucy Kennedy", "TD Tutoring", "Study Hat"] },
      wave2Cold: { sent: 3, sentTo: ["Emily Kendall", "Sabah Hadi", "The Exam Coach"] },
      totalColdSent: 10,
      calendarHolds: 9,
      lastAction: "Sent-ledger + audit scripts; pricing aligned to £19.99 + LEVELFIELD",
      blockedOn: ["Partner slot confirmations (voice not email)", "You running 10-min calls (b2-6)", "Andy until 30 Jun", "Kimi reconnect for WA/Gmail audit"],
      manualNext: [
        "python3 scripts/marketing-execute.py (reads sent-ledger → one next action)",
        "Level Field: viral_sequence ONCE if poster not sent — outreach/execute/NEXT-LEVEL-FIELD.md",
        "DM sweep: outreach/execute/DM-SWEEP-TODAY.md after Kimi up",
        "Partner calls: outreach/partner-calls/CALL-BRIEFS.md (MTM Tue 10, no more emails)",
      ],
    },
  },
  northStar: {
    metricsSource: "progress/metrics-snapshot.js (run: python3 scripts/fetch-metrics-snapshot.py)",
    metricsFetchedAt: "2026-06-07T20:17:10Z",
    mrr: 290,
    mrrTarget: 10000,
    mrrTarget3mo: 2000,
    payingCustomers: 8,
    activePaying: 6,
    activePayingElevenPlusCheckout: 4,
    legacyOtherPaying: 2,
    trialingApi: 2,
    payingTarget: 500,
    waCommunity: 600,
    anchorEvent: "Live mock - 14 June 2026",
    anchorDate: "2026-06-14",
    deadlineMilestone: "2026-06-20",
    liveMockEnrolledReal: 22,
    liveMockEnrolledDisplayed: 77,
    liveMockRevenueGbpPlus: 400,
    liveMockPromoSpotsRemaining: 3,
    revenueSprintTargetGbp: 1000,
    revenueSprintNewConversions: 25,
    mockEnrolledTarget: 50,
    mockEnrolledStretch: 80,
  },
  rules: [
    "Lead with QE proof - you sat 11+ and you're at QE Boys.",
    "Parents buy proof (mock score), not apps. Offer free first, paid second.",
    "600 WhatsApp members = warmest pipe. Convert before cold scale.",
    "Partners say yes on a call - email only books the call.",
    "When they want a call: book the earliest slot (today/tomorrow) - confirm + Meet within minutes.",
    "Anchor price vs tutor (£40–60/hr), not vs free Bond papers.",
    "Level Field: sprint already announced - DM only for scores/PREMIUM; no Y4/Y5/Y6 broadcast.",
    "WA group already knows Premium - sell sprint + more attempts, not a launch.",
    "Lead with age: you sat 11+ recently and remember the pressure firsthand.",
    "Do not contact Sutton 11 Plus or Robert Lomax.",
    "Browser automation: Kimi WebBridge only - never Cursor IDE browser.",
    "No paid Meta ads until trial→paid > 25%. Referrals at 30+ paid only.",
  ],
  blocks: [
    {
      id: "block-1",
      number: 1,
      title: "Ship the funnel",
      subtitle: "Fix conversion before any big promotion",
      status: "done",
      owner: "mixed",
      why: "100 parents to a broken funnel wastes trust forever.",
      steps: [
        { id: "b1-1", title: "Production env VITE_APP_TRACK=11PLUS", status: "done", owner: "codex", when: "Before Block 2" },
        { id: "b1-2", title: "Live mock £10 everywhere (UI + Stripe)", status: "done", owner: "codex", when: "Before Block 2", note: "price_1Tf63lQYWoowhxMZKU2Z2AWY" },
        { id: "b1-3", title: "Start free practice CTA on landing", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-4", title: "Partner ?ref= banner on landing", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-5", title: "Post-mock parent report (score + weak topics)", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-6", title: "Honest copy: 1 mock/day (not 2)", status: "done", owner: "cursor", when: "Before Block 2" },
        { id: "b1-7", title: "Deploy to production", status: "done", owner: "codex", when: "Before Block 2", note: "Commits 497af2b + 0e1895a" },
        { id: "b1-8", title: "30-min logged-in E2E test", status: "done", owner: "niketh", when: "2026-05-20", note: "E2E passed - signup, onboarding, mock, parent card, £10 checkout" },
      ],
    },
    {
      id: "block-2",
      number: 2,
      title: "Partner calls",
      subtitle: "Automation done - 0/5 calls booked · waiting on replies",
      status: "active",
      owner: "niketh",
      why: "All outreach sent (Tier A + 10 cold). Blocked on partner slot confirms and you running calls.",
      steps: [
        { id: "b2-0", title: "Inbox prep (5 min)", status: "done", owner: "niketh", when: "2026-06-07", note: "Kimi scan · no new Tier A replies · Mathsaurus auto-reply only" },
        { id: "b2-1", title: "Book call - Chris (Eleven Plus Success)", status: "active", owner: "niketh", when: "Chased 7 Jun", contact: "tutor@elevenplussuccess.com · 07771740569", note: "Email chase Thu 12/Fri 13 Jun · WA wa.me opened via Kimi" },
        { id: "b2-2", title: "Book call - Andy (Pinner Road)", status: "pending", owner: "niketh", when: "After 30 Jun", contact: "prlcharrow@gmail.com", note: "On holiday until 30 Jun · early July call offered 6 Jun" },
        { id: "b2-3", title: "Book call - David (11 Plus Hub)", status: "active", owner: "niketh", when: "Awaiting reply", contact: "info@11plushub.com", note: "6 Jun slots Thu 12/Fri 13 Jun · no reply yet" },
        { id: "b2-4", title: "Book call - Mock Test Masters", status: "active", owner: "niketh", when: "Awaiting reply", contact: "info@mocktestmasters.com", note: "6 Jun slots Tue 10/Wed 11 Jun · no reply yet" },
        { id: "b2-5", title: "Book call - Cecile (Frenchie Mummy)", status: "active", owner: "niketh", when: "Login reply sent", contact: "cecile@thefrenchiemummy.com", note: "She reported paywall/kicked out · login-fix sent 7 Jun · Thu 12/Fri 13 slots" },
        { id: "b2-6", title: "Run 10-min call script on each", status: "pending", owner: "niketh", when: "When slot confirmed", note: "Blocked - 0 calls booked" },
        { id: "b2-7", title: "Send ?ref= link + caption after each yes", status: "pending", owner: "niketh", when: "Within 1h of call" },
        { id: "b2-8", title: "Manual deck attach if they reply DECK", status: "pending", owner: "niketh", when: "As needed", note: "outreach/assets/Gradlify-Partner-Overview.pptx" },
        { id: "b2-9", title: "Priority 2 - only if they replied YES", status: "pending", owner: "niketh", when: "After inbox check", note: "7 Jun scan: no YES replies · Honest Mum, Willow, etc." },
        { id: "b2-10", title: "Tina closed · Sutton · Robert never", status: "done", owner: "niketh", when: "2026-06-07", note: "Tina: no commission close sent · Sutton + Robert: do not contact" },
        { id: "b2-11", title: "Wave 1 Tier C cold outreach", status: "done", owner: "niketh", when: "2026-06-06", note: "7 sent · Robert excluded" },
        { id: "b2-12", title: "Wave 2 cold outreach", status: "done", owner: "niketh", when: "2026-06-07", note: "Emily Kendall, Sabah Hadi, The Exam Coach" },
      ],
    },
    {
      id: "block-3",
      number: 3,
      title: "Mock poster + assets",
      subtitle: "HTML draft ready - export PNG and share",
      status: "active",
      owner: "niketh",
      why: "GCs share posters more than bare links.",
      steps: [
        { id: "b3-1", title: "Poster 1080×1080 (Canva/Figma)", status: "done", owner: "cursor", when: "2026-06-07", note: "outreach/assets/14-june-mock-poster.html - open in browser, screenshot/export" },
        { id: "b3-2", title: "Story image 1080×1920", status: "done", owner: "cursor", when: "2026-06-07", note: "Same HTML file - story panel included" },
        { id: "b3-3", title: "Save to outreach/assets/", status: "active", owner: "niketh", when: "Today", note: "Export PNGs from HTML → 14-june-mock-poster.png + story.png" },
      ],
    },
    {
      id: "block-4",
      number: 4,
      title: "Convert ~450 WhatsApp",
      subtitle: "Sent-ledger driven — poster once, then reminders + DMs only",
      status: "active",
      owner: "niketh",
      why: "Sprint announced. Date locked Sun 14 Jun 4-6:30pm. Do not re-launch or poll.",
      steps: [
        { id: "b4-0", title: "Mock timing poll", status: "skipped", owner: "niketh", when: "N/A", note: "Date locked - poll skipped per sent-ledger" },
        { id: "b4-1", title: "Sprint launch (Y4/Y5/Y6)", status: "done", owner: "niketh", when: "Prior", note: "Already announced - do not repeat" },
        { id: "b4-2", title: "Level Field viral sequence (poster+caption+forward)", status: "active", owner: "niketh", when: "Once if not sent", note: "outreach/execute/NEXT-LEVEL-FIELD.md · check sent-ledger mock_poster status" },
        { id: "b4-3", title: "DM sweep (scores/PREMIUM/price)", status: "active", owner: "niketh", when: "Daily 60-90min", note: "scripts/dm-sweep-agent.py · parent-conversion-tracker.csv" },
        { id: "b4-4", title: "Message 5 paying subscribers for referrals", status: "pending", owner: "niketh", when: "After poster", note: "outreach/distribution/paying-subs-referral.txt" },
        { id: "b4-5", title: "Spots/weekend reminders", status: "pending", owner: "niketh", when: "After poster sent", note: "mock-spots-reminder.txt · mock-weekend-reminder.txt" },
        { id: "b4-6", title: "Get 3 forwards into new GCs", status: "pending", owner: "niketh", when: "Ongoing", note: "mock-forward-ask + paying sub forwards" },
        { id: "b4-7", title: "Post-mock conversion (24h)", status: "pending", owner: "niketh", when: "15 Jun", note: "outreach/mock-day/15-jun-conversion-dm.txt" },
      ],
    },
    {
      id: "block-5",
      number: 5,
      title: "Facebook groups",
      subtitle: "Strangers - post feels like help, not ad",
      status: "pending",
      owner: "niketh",
      why: "Only works after Block 1 E2E passes.",
      steps: [
        { id: "b5-0", title: "Join Reddit r/11PlusHelp + answer 2 threads", status: "pending", owner: "niketh", when: "This week", note: "Helpful first - Template 3 style" },
        { id: "b5-1", title: "Join 7 FB groups (Barnet, Enfield, Herts, Kent)", status: "pending", owner: "niketh", when: "This week" },
        { id: "b5-2", title: "Comment helpfully 2–3 days before any post", status: "pending", owner: "niketh", when: "While waiting approval" },
        { id: "b5-3", title: "First story post per group (QE angle)", status: "pending", owner: "niketh", when: "After approved" },
        { id: "b5-4", title: "5 cold FB DMs (Template 1 or 2)", status: "pending", owner: "niketh", when: "Weekly Friday" },
        { id: "b5-5", title: "Mumsnet: answer 2× 11+ threads", status: "pending", owner: "niketh", when: "Weekly Tuesday" },
        { id: "b5-6", title: "Reminder post ~7 June", status: "active", owner: "niketh", when: "2026-06-07", note: "Due today - use community-posts.md" },
      ],
    },
    {
      id: "block-6",
      number: 6,
      title: "14 June mock day",
      subtitle: "Score moment = when parents pay",
      status: "pending",
      owner: "niketh",
      why: "Follow up within 24h or you lose them.",
      steps: [
        { id: "b6-1", title: "13 June - GC reminder + tech test", status: "pending", owner: "niketh", when: "2026-06-13" },
        { id: "b6-2", title: "14 June - run mock + attendee sheet", status: "pending", owner: "niketh", when: "2026-06-14" },
        { id: "b6-3", title: "Within 24h - 1:1 every attendee (score + gap)", status: "pending", owner: "niketh", when: "2026-06-15", note: "Use objection cards on replies" },
        { id: "b6-4", title: "Voice note 3 hottest leads", status: "pending", owner: "niketh", when: "By 20 June" },
        { id: "b6-5", title: "Target: 3 new £20/mo subs from mock", status: "pending", owner: "niketh", when: "2026-06-20" },
      ],
    },
    {
      id: "block-7",
      number: 7,
      title: "Weekly rhythm",
      subtitle: "Playbook Part 5 - compound every week",
      status: "active",
      owner: "niketh",
      why: "Growth = weekly actions logged, not one big push.",
      steps: [
        { id: "b7-1", title: "Mon - 1 helpful FB post (no sell)", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-2", title: "Tue - 2–3 Reddit/Mumsnet answers", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-3", title: "Wed - 5 warm WA personal DMs", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-4", title: "Thu - 1 IG/TikTok (QE/11+ angle)", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-5", title: "Fri - 5 cold FB DMs + partner call", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-6", title: "Sat - log DMs / replies / conversions", status: "pending", owner: "niketh", when: "Weekly" },
        { id: "b7-7", title: "Sun - plan week + 5 new targets", status: "pending", owner: "niketh", when: "Weekly · 20 min" },
      ],
    },
    {
      id: "block-8",
      number: 8,
      title: "Referral programme",
      subtitle: "At 30+ paid - not yet",
      status: "pending",
      owner: "niketh",
      why: "Playbook: referrals compound after base. You have 6 paid now.",
      steps: [
        { id: "b8-1", title: "Wait until 30+ paying customers", status: "pending", owner: "niketh", when: "Later", note: "Currently 6 - focus WA + mock + partners first" },
        { id: "b8-2", title: "Launch: refer a friend = free month both", status: "pending", owner: "niketh", when: "At 30+" },
        { id: "b8-3", title: "Unique ?ref= per member + monthly reminder", status: "pending", owner: "niketh", when: "At 30+" },
      ],
    },
  ],
  milestones: [
    { id: "m1", label: "Block 1 deployed", date: "2026-06-05", status: "done" },
    { id: "m2", label: "Block 1 E2E tested", date: "2026-05-20", status: "done" },
    { id: "m3", label: "5 partner calls booked (0/5)", date: "2026-06-08", status: "pending" },
    { id: "m4", label: "2 partners live with ?ref= (0/2)", date: "2026-06-12", status: "pending" },
    { id: "m5", label: "FB reminder posts", date: "2026-06-07", status: "active" },
    { id: "m6", label: "Live mock day", date: "2026-06-14", status: "pending" },
    { id: "m7", label: "3 new subs from mock", date: "2026-06-20", status: "pending" },
    { id: "m8", label: "WA PREMIUM sprint done", date: "2026-06-12", status: "pending" },
    { id: "m9", label: "Month 1: 5–10 paid from 600 WA", date: "2026-06-30", status: "pending" },
  ],
  successBy20June: [
    { id: "s1", label: "Block 1 shipped and tested", done: true },
    { id: "s2", label: "5 partner calls done (or 3+ completed)", done: false },
    { id: "s3", label: "2 partners live with ?ref= links", done: false },
    { id: "s4", label: "WA 7-day sprint + PREMIUM launch sent", done: false },
    { id: "s5", label: "Poster in 3+ GCs + 5+ FB groups", done: false },
    { id: "s6", label: "20 families sit 14 June mock", done: false },
    { id: "s7", label: "3 new paid subs within 6 days of mock", done: false },
    { id: "s8", label: "Saturday metrics logged 2 weeks in a row", done: false },
  ],
  doNotYet: [
    "Mass DM to Mathsaurus / big YouTubers",
    "Paid Meta ads",
    "Referral programme (until 30+ paid)",
    "School letters / tutor centre visits (slow - defer)",
    "Long email negotiations (book the call)",
    "Sutton 11 Plus",
    "Robert Lomax (do not contact)",
    "Cursor IDE browser for Gmail/WA (use Kimi only)",
  ],
};
