/** Auto-generated by scripts/partner-reply-agent.py - do not edit */
window.GRADLIFY_LIVE_FEED = {
  "generatedAt": "2026-06-07 sent-ledger audit-driven ops",
  "recentUpdates": [
    {
      "org": "Outreach pipeline",
      "kind": "done",
      "kindLabel": "Completed",
      "preview": "10 cold emails sent (Wave 1: 7, Wave 2: 3). Tier A: all 5 contacted.",
      "action": "done",
      "note": null,
      "subject": "Block 2 automation"
    },
    {
      "org": "Cecile \u00b7 Frenchie Mummy",
      "kind": "login_issue",
      "kindLabel": "Login / access issue",
      "preview": "Paywall + kicked out \u2014 login-fix email sent with Thu 12 / Fri 13 call slots.",
      "action": "auto_reply_sent",
      "note": "Awaiting her time confirm",
      "subject": "11+ paid/affiliate collab?"
    },
    {
      "org": "Chris \u00b7 Eleven Plus Success",
      "kind": "delayed",
      "kindLabel": "Asked for more time",
      "preview": "Not yet \u2014 will look next week. Chased 7 Jun (email + WA).",
      "action": "already_handled",
      "note": "Thu 12 / Fri 13 slots offered",
      "subject": "Re: 11+ affiliate partnership?"
    },
    {
      "org": "Mathsaurus",
      "kind": "auto_reply",
      "kindLabel": "Auto-reply (no action)",
      "preview": "Thank you for contacting Mathsaurus Support. To help you resolve your issue as quickly as possible, we've included answers to common questions below. You can also find detailed FAQ",
      "action": "ignored_auto_reply",
      "note": null,
      "subject": "Thank you for contacting Mathsaurus Re: Quick call about a collab?"
    },
    {
      "org": "Eleven Plus Success",
      "kind": "delayed",
      "kindLabel": "Asked for more time",
      "preview": "Not yet no. I will next week   Kind regards   Chris Moore Head teacher Eleven Plus Success (Part of One to One Tutoring) M: 07771740569 E: tutor@elevenplussuccess.com BOOKINGS:\u00a0htt",
      "action": "already_handled (auto_reply_sent)",
      "note": "Partner asked for more time \u2014 slots re-offered once only",
      "subject": "Re: 11+ affiliate partnership?"
    },
    {
      "org": "Frenchie Mummy",
      "kind": "login_issue",
      "kindLabel": "Login / access issue",
      "preview": "It is still asking me to pay? And it just kicked me out too. I keep going back to the home page?  \u00a0  Thanks  \u00a0  Cecile  \u00a0  From: Niketh Putta <niketh13putta@gmail.com> Sent: 02 Jun",
      "action": "already_handled (auto_reply_sent)",
      "note": null,
      "subject": "11+ paid/affiliate collab?"
    },
    {
      "org": "Mock Test Masters",
      "kind": "delayed",
      "kindLabel": "Asked for more time",
      "preview": "Hi Niketh   We are not free until 3rd\u00a0 June.     Kind regards   The Mock Test Masters team Web: www.mocktestmasters.com  The No.1 mock test provider  Email: info@mocktestmasters.co",
      "action": "already_handled (auto_reply_sent)",
      "note": null,
      "subject": "Quick clarification: 11+ affiliate partnership"
    },
    {
      "org": "Mock Test Masters",
      "kind": "slot_confirm",
      "kindLabel": "Confirmed slot",
      "preview": "Goof morning Niketh.   This sounds interesting, thank you for contacting us. Yes, please send a sample report.     Kind regards Sandra  The Mock Test Masters team Web: www.mocktest",
      "action": "already_handled (auto_reply_failed)",
      "note": null,
      "subject": "Free readiness check to support 11+ mock-test parents"
    }
  ],
  "nextThree": [
    {
      "n": 1,
      "title": "Level Field viral sequence (ONCE if poster not sent)",
      "why": "Sent-ledger: sprint done, poll skipped, poster status unknown",
      "how": [
        "Check: python3 scripts/kimi-state-audit.py",
        "Poster PNG + outreach/wa/mock-gc-caption.txt",
        "2 min later: mock-forward-ask.txt",
        "Do NOT: poll, sprint launch, mock-14-june-announce.txt"
      ],
      "file": "outreach/execute/NEXT-LEVEL-FIELD.md",
      "block": "b4-2",
      "minutes": 15
    },
    {
      "n": 2,
      "title": "DM sweep — scores / PREMIUM / price",
      "why": "\u00a31k sprint: conversion happens in DMs not group broadcasts",
      "how": [
        "python3 scripts/dm-sweep-agent.py (Kimi)",
        "Log: outreach/parent-conversion-tracker.csv",
        "Scripts: dm-premium.txt, dm-too-expensive.txt"
      ],
      "file": "outreach/execute/DM-SWEEP-TODAY.md",
      "block": "b4-3",
      "minutes": 60
    },
    {
      "n": 3,
      "title": "MTM call Tue 10 / Wed 11 (not another email)",
      "why": "Sandra interested + wants sample report; 0 calls booked",
      "how": [
        "Brief: outreach/partner-calls/CALL-BRIEFS.md",
        "Screen-share sample report on call",
        "Send ?ref=MTM after verbal yes"
      ],
      "file": "outreach/partner-calls/CALL-BRIEFS.md",
      "block": "b2-4",
      "minutes": 10
    }
  ],
  "autoActionsToday": []
};
