/**
 * Playbook knowledge — Growth + Sales Objection docs (integrated 2026-06-06)
 */
window.GRADLIFY_REFERENCE = {
  coreEdge: {
    title: "Your unfair advantage",
    lines: [
      "You sat the 11+ only a few years ago — you remember the pressure, not theory.",
      "QE Boys — proof you know what top grammar entry actually takes.",
      "Built Gradlify at 15 from what worked, not what tutors sell.",
      "Parents pay £40–60/hr (£160–240/mo). Founder rate £19.99/mo = less than half one session.",
    ],
    useEverywhere: "I did the 11+ recently — I still remember how stressful it was. I'm at QE now and built Gradlify for families who want that path without £2k/month tuition.",
  },
  levelFieldVoice: {
    title: "The Level Field — how Niketh talks",
    file: "outreach/level-field-voice.md",
    funnel: "Reply Y4/Y5/Y6 → DM ?ref=LEVELFIELD → mock → score → guidance → PREMIUM",
    tone: "Helpful peer who sat 11+ recently. Short blocks. Genuine questions. No pressure.",
    groupRules: [
      "No payment links in the group — DM only",
      "They already know Premium — not a launch",
      "Convert on completed mock + score, not interest",
      "£19.99/mo real price — anchor vs tutor hour, not fake MSRP",
    ],
    files: {
      day1: "outreach/wa/day1-relatability.txt",
      day2: "outreach/wa/day2-tips.txt",
      day3: "outreach/wa/day3-quiz.txt",
      day4: "outreach/wa/day4-engage.txt",
      day5: "outreach/wa/day5-founder-close.txt",
      dmYear: "outreach/wa/dm-year-reply.txt",
      dmPremium: "outreach/wa/dm-premium.txt",
    },
  },
  pricingPsychology: {
    realPrice: "£19.99/mo is your actual price. Do not threaten a jump to £40 — parents will not sign up if they think that is coming.",
    tutorAnchor: "One tutor hour = £40–60. Gradlify = £19.99 for the whole month. Compare hours, not fake was/now product prices.",
    waFraming: "Urgency without price hike: founder link / extended trial / personal DM closes Friday — not price goes up.",
    scarcity: "They already know Premium. Close on: last chance for founder perks, [X] families joined, link expires.",
    avoid: "Never say standard £39.99 or £40/mo for Gradlify. That reads as unaffordable.",
  },
  fiveAngles: [
    { id: "recent", name: "Recently did 11+", for: "WA group + anxious Y5 parents", hook: "I was in your child's shoes 2–3 years ago. I know exactly what the build-up feels like." },
    { id: "qe", name: "QE / Grammar route", for: "North London Y4–5, QE aspirational", hook: "I go to QE — I know what it takes. Gradlify is what I wish my parents had." },
    { id: "exam", name: "11+ specialist", for: "Any grammar school parent nationally", hook: "Most kids are underprepared — wrong practice. Mocks + readiness tracking show real gaps." },
    { id: "antitutor", name: "Anti-tutor", for: "Paying tutor or shocked by £160–240/mo", hook: "£20/mo for unlimited mocks + analytics vs one tutor hour." },
    { id: "anxiety", name: "Parent anxiety", for: "FB groups, forums — worried parents", hook: "Readiness tracker — no guessing if they're ready before exam day." },
    { id: "scarcity", name: "Early habit", for: "Year 4 parents", hook: "Places are limited — kids who start early and practice consistently win." },
  ],
  weeklyRhythm: [
    { day: "Mon", action: "1 helpful FB group post (tip/story, no sell)" },
    { day: "Tue", action: "2–3 genuine answers on Reddit or Mumsnet" },
    { day: "Wed", action: "5 personal DMs to warm WhatsApp members" },
    { day: "Thu", action: "1 short IG/TikTok (QE/11+ angle)" },
    { day: "Fri", action: "5 cold DMs to new parents from FB (Template 1/2)" },
    { day: "Sat", action: "Log: DMs sent, replies, conversions" },
    { day: "Sun", action: "Plan next week + 5 new outreach targets (20 min)" },
  ],
  monthlyTargets: [
    { month: "Month 1", free: "20–30 new WA members", paid: "5–10 Premium from existing 600" },
    { month: "Month 2", free: "50 new community", paid: "10–15 new paid (warm + cold)" },
    { month: "Month 3", free: "100 new free/mo baseline", paid: "20+ new paid" },
    { month: "6 mo", free: "200+ free/mo", paid: "40–60 paid + referral flywheel" },
  ],
  metrics: [
    "DMs sent / replies / conversions (weekly)",
    "Source of every paying user",
    "Trial starts → paid %",
    "Partner calls booked / closed",
    "Mock attendees → paid within 7 days",
  ],
  conversationFlow: [
    "Open with a question (What year is your child in?)",
    "Share story in 2 sentences (QE + why you built Gradlify)",
    "Match angle to their situation",
    "Invite free first — not paid push",
    "Handle objection (agree → reframe → question)",
    "Close soft: send link, look in own time",
    "One follow-up at 5–7 days — max twice",
  ],
  universalClose: "That makes complete sense — start with the free version. No card, no commitment. If it doesn't help, you've lost nothing. If it does, you'll know before the exam.",
  objections: [
    { id: "price", label: "Too expensive", mean: "Wants value proof", response: "Anchor tutor £40–60/hr. Gradlify £20/mo = less than one session/week. Start free.", close: "Can I send the free link so you can compare side by side?" },
    { id: "tutor", label: "Already has a tutor", mean: "Fears replacement", response: "Complement not replacement. Tutor teaches, Gradlify tracks gaps between sessions.", close: "Worth trying free alongside this term?" },
    { id: "year", label: "Not Year 5 yet", mean: "Thinks it's early", response: "Year 4 habit building = confidence. You started Year 4.", close: "Free plan now — light practice, no pressure." },
    { id: "fit", label: "Not sure it's right fit", mean: "Needs personal relevance", response: "What would right fit look like? Point them to the right feature first.", close: "Try free version for their specific gap?" },
    { id: "think", label: "Need to think / later", mean: "Interested but no urgency", response: "Free plan now while thinking. Exam creeps up fast.", close: "Send free trial link now — no action needed yet?" },
    { id: "proof", label: "How do I know it works?", mean: "Wants evidence", response: "QE result + you built it. Analytics = targeted not random. Free trial 30 days.", close: "What would working look like for your child?" },
    { id: "wontuse", label: "Child won't use it", mean: "Burned by apps before", response: "Mock format ≠ worksheets. Score loop engages. Parent dashboard works even if kid does 5 min.", close: "First session together on the sofa?" },
    { id: "free", label: "Free resources exist", mean: "Doesn't see paid delta", response: "Free gives practice not clarity. Gradlify tells what to do next.", close: "Try free plan — see if analytics add something?" },
    { id: "age", label: "You're only 15", mean: "Trust gap", response: "Sat 11+ recently — current format. Platform is real at gradlify.com.", close: "Walk through anything specific — no signup pressure." },
    { id: "school", label: "No target school yet", mean: "Thinks prep waits on school choice", response: "Core 11+ content same across schools. Analytics help pick later.", close: "Want competitive score ranges for this area?" },
  ],
  impactAssessment: {
    headline: "What actually moves MRR from £121 → £2k",
    high: [
      "WA founder-rate close (they know Premium — urgency + your recent-11+ story)",
      "Landing comparison section: Gradlify vs tutor vs workbooks (cold traffic)",
      "14 June mock → 24h personalised follow-up with objections script",
      "Partner calls live (distribution you don't have alone)",
      "QE story + anti-tutor anchor on every parent DM",
    ],
    medium: [
      "FB groups with story-first comments (already in Block 5)",
      "5 cold DMs/week from playbook templates",
      "Saturday metrics log (fixes what's not working)",
    ],
    lowNow: [
      "IG/TikTok before partners + WA convert (long burn)",
      "School letters / in-person tutor visits (slow)",
      "Referral programme (wait until 30+ paid — you're at 6)",
      "Paid Meta ads (still no until trial→paid > 25%)",
    ],
    verdict: "Playbooks raise conversion quality and WhatsApp monetisation — likely +30–50% on same traffic if you execute Part 3 + objection handling. They do NOT replace Block 2 partner distribution. Do WA sprint this week in parallel with partner calls.",
  },
  channels: {
    priority: ["WhatsApp 600 warm", "Partner affiliates", "FB groups", "14 June mock", "Reddit/Mumsnet", "IG/TikTok"],
    rules: {
      facebook: "No sales link first posts. Comment helpfully 3–5x before own post. Story > features.",
      reddit: "Thorough helpful answer first. Mention Gradlify only if genuinely useful.",
      whatsapp: "Voice note + text for conversion. Personal DM top 20–30 engagers.",
    },
  },
};
