#!/usr/bin/env python3
"""Fetch live Gradlify metrics from production APIs → progress/metrics-snapshot.js"""
from __future__ import annotations

import json
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "progress" / "metrics-snapshot.js"

SUPABASE_URL = "https://gknnfbalijxykqycopic.supabase.co"
ANON_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrbm5mYmFsaWp4eWtxeWNvcGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzgxMzEsImV4cCI6MjA3MjIxNDEzMX0."
    "nbJ6GgZmJ5ZPiTkYa_Y5C2G6Sep9IF8juXv4uU_CMDU"
)
MOCK_SLUG = "both_subjects_live_mock"


def post_json(path: str, body: dict) -> dict:
    url = f"{SUPABASE_URL}/functions/v1/{path}"
    payload = json.dumps(body).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {ANON_KEY}",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode())


def main() -> int:
    fetched_at = datetime.now(timezone.utc).isoformat()

    mock = post_json("live-mock-signup-count", {"mockSlug": MOCK_SLUG})
    analytics = post_json("admin-analytics", {"days": 14})

    if not analytics.get("ok"):
        raise SystemExit(f"admin-analytics failed: {analytics}")

    data = analytics["data"]
    kpis = data.get("kpis", {})
    totals = data.get("totals", {})
    paying_users = data.get("payingUsers", [])

    active = [u for u in paying_users if u.get("status") == "active" and not u.get("cancel_at_period_end")]
    trialing = [u for u in paying_users if u.get("status") == "trialing" and not u.get("cancel_at_period_end")]

    live_mock_api = kpis.get("liveMock") or {}
    subs_api = kpis.get("subscriptions") or {}

    # Legacy £20/mo subs on other checkout (gcse price path) count as 11+ — Niketh-confirmed: 2
    legacy_other = subs_api.get("legacyOtherPaying")
    api_active = subs_api.get("activePaying") or len(active)
    api_mrr = kpis.get("earnings", {}).get("monthly", 0) or 0
    if legacy_other is None:
        legacy_other = 2
        active_paying = api_active + legacy_other
        mrr_gbp = round(api_mrr + (legacy_other * 20), 2)
        legacy_note = "Manual include until admin-analytics deploy picks up legacy gcse-price subs"
    else:
        active_paying = api_active
        mrr_gbp = round(api_mrr, 2)
        legacy_note = None

    trialing_count = subs_api.get("trialing") or len(trialing)

    snapshot = {
        "fetchedAt": fetched_at,
        "source": "live-mock-signup-count + admin-analytics (production)",
        "warning": "Do not use stale docs — re-run this script before marketing decisions",
        "subscriptions": {
            "activePaying": active_paying,
            "trialing": trialing_count,
            "premiumFunnel": active_paying + trialing_count,
            "legacyOtherPaying": legacy_other,
            "mrrGbp": mrr_gbp,
            **({"legacyNote": legacy_note} if legacy_note else {}),
        },
        "liveMock": {
            "slug": MOCK_SLUG,
            "enrolledReal": live_mock_api.get("enrolledReal") or mock.get("count") or totals.get("liveMockEnrolled"),
            "enrolledDisplayed": live_mock_api.get("enrolledDisplayed") or mock.get("displayedCount"),
            "revenueGbp": live_mock_api.get("revenueGbp"),
            "paidCheckoutSessions": live_mock_api.get("paidCheckoutSessions"),
            "currentPriceGbp": mock.get("currentPriceGbp") or mock.get("standardPriceGbp"),
            "promoCode": mock.get("promoCode", "LEVELFIELD"),
            "promoSpotsRemaining": mock.get("promoSpotsRemaining"),
        },
        "profiles": {
            "totalSignups11plus": totals.get("totalSignups"),
            "signupsLast7d": kpis.get("signups", {}).get("last7d"),
        },
        "activePayingEmails": [u.get("email") for u in active],
        "trialingEmails": [u.get("email") for u in trialing],
    }

    OUT_PATH.write_text(
        "/** Auto-generated by scripts/fetch-metrics-snapshot.py — do not edit */\n"
        f"window.GRADLIFY_METRICS = {json.dumps(snapshot, indent=2)};\n"
    )
    print(json.dumps(snapshot, indent=2))
    print(f"\nWrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
