import csv
import json

questions = [
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|bidmas",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Calculate the value of: 4 + 5 × 3 - 2",
        "correct_answer": "17",
        "wrong_answers": '{"25","15","13"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: BIDMAS]\nStep 1: Look out for Multiplication (M) and do it before Addition (A).\nStep 2: Calculate 5 × 3 = 15.\nStep 3: Replace that in the sum: 4 + 15 - 2.\nStep 4: Add and Subtract from left to right: 19 - 2 = 17.\nFinal answer: 17."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|bidmas",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "What is the answer to: 24 ÷ (6 - 2) + 3²",
        "correct_answer": "15",
        "wrong_answers": '{"11","10","21"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 75,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Order of Operations]\nStep 1: Always do Brackets (B) first: 6 - 2 = 4.\nStep 2: Next is Indices (I): 3² = 9.\nStep 3: Our sum is now 24 ÷ 4 + 9.\nStep 4: Division (D) before Addition: 24 ÷ 4 = 6.\nStep 5: Finally add them: 6 + 9 = 15.\nFinal answer: 15."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|addition-subtraction",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Add 45.6 and 12.04 together.",
        "correct_answer": "57.64",
        "wrong_answers": '{"57.10","16.60","57.06"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Stack and Fill]\nStep 1: Write both numbers in column format with the decimal points perfectly aligned.\nStep 2: Add a zero placeholder to 45.6 so it becomes 45.60.\nStep 3: Add straight down: 45.60 + 12.04 = 57.64.\nTip: Most mistakes happen by misaligning the tenths and hundredths columns!"
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|multiplication-division",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A box contains 24 chocolates. If a school orders 135 boxes, how many chocolates are there in total?",
        "correct_answer": "3240",
        "wrong_answers": '{"2860","3140","3360"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 90,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Formal Written Methods]\nStep 1: We need to calculate 135 × 24.\nStep 2: Use the formal long multiplication method. First, multiply 135 by 4 to get 540.\nStep 3: Crucial Step! Add your placeholder zero for the next line, because you are multiplying by 20, not 2.\nStep 4: 135 × 2(0) = 2700.\nStep 5: Add them up: 540 + 2700 = 3240.\nFinal answer: 3240."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|place-value",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Round 72,485 to the nearest hundred.",
        "correct_answer": "72,500",
        "wrong_answers": '{"72,400","72,000","73,000"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Rounding Rule]\nStep 1: Locate the hundreds column. The digit is `4`.\nStep 2: Look at the digit immediately to the right, which is `8` (in the tens column).\nStep 3: Because 8 is 5 or more, we must round UP the hundreds digit.\nStep 4: The 4 becomes a 5, and all digits to the right become 0.\nFinal answer: 72,500."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|factors-multiples-primes",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Which of these is the prime factorization of 60?",
        "correct_answer": "2² × 3 × 5",
        "wrong_answers": '{"2 × 3² × 5","2 × 4 × 5","2² × 15"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Factor Tree]\nStep 1: Break 60 down into any two factors, e.g., 6 and 10.\nStep 2: Look at 6. It breaks into 2 and 3. Both are prime, so circle them.\nStep 3: Look at 10. It breaks into 2 and 5. Both are prime, so circle them.\nStep 4: Gather all the circled primes: 2 × 2 × 3 × 5.\nStep 5: Write using indices: 2² × 3 × 5.\nFinal answer: 2² × 3 × 5"
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|factors-multiples-primes",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Find the Highest Common Factor (HCF) of 36 and 48.",
        "correct_answer": "12",
        "wrong_answers": '{"6","24","144"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 120,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: HCF and LCM]\nStep 1: Prime factorize 36 (2×2×3×3) and 48 (2×2×2×2×3).\nStep 2: Place them in a Venn diagram. The shared primes go in the middle.\nStep 3: Both numbers share two 2s and one 3. (2, 2, 3).\nStep 4: For the HCF, multiply the numbers in the middle together.\nStep 5: 2 × 2 × 3 = 12.\nFinal answer: 12."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|decimals-percentages",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Convert 3/8 into a percentage.",
        "correct_answer": "37.5%",
        "wrong_answers": '{"38%","3.8%","375%"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 90,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: FDP Connection]\nStep 1: A great mental maths shortcut is knowing that 1/8 is equal to 0.125 or 12.5%.\nStep 2: Since we have 3/8, we multiply 12.5% by 3.\nStep 3: 12.5 × 3 = 37.5.\nTip: If you didn't know the shortcut, you could divide 3 by 8 using bus stop division (3.000 ÷ 8 = 0.375) and then multiply by 100."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|ratio",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Alice and Bob share £45 in the ratio 4:5. How much does Bob receive?",
        "correct_answer": "£25",
        "wrong_answers": '{"£20","£30","£15"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Sharing in a Ratio]\nStep 1: Calculate the total number of parts. 4 + 5 = 9 parts in total.\nStep 2: Find the value of 1 part dividing the total amount by the number of parts. £45 ÷ 9 = £5.\nStep 3: Bob has 5 parts. Multiply his parts by the value of 1 part: 5 × £5 = £25.\nFinal answer: £25."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|basics",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A number machine multiplies an input by 3 and then subtracts 5. If the input is 7, what is the output?",
        "correct_answer": "16",
        "wrong_answers": '{"26","14","6"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Function Machine]\nStep 1: Follow the machine left to right.\nStep 2: Input is 7. First instruction: Multiply by 3. 7 × 3 = 21.\nStep 3: Second instruction: Subtract 5. 21 - 5 = 16.\nFinal answer: 16."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|equations",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Solve for x: 4x + 7 = 23",
        "correct_answer": "x = 4",
        "wrong_answers": '{"x = 5","x = 6","x = 3.5"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Balance Method]\nStep 1: Remember, whatever you do to one side of the equation, you must do to the other.\nStep 2: Subtract 7 from both sides to isolate the 4x. This leaves 4x = 16.\nStep 3: Divide both sides by 4 to find the value of a single x.\nStep 4: 16 ÷ 4 = 4.\nFinal answer: x = 4."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|sequences",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "The first four terms of a sequence are 5, 9, 13, 17. What is the nth term rule?",
        "correct_answer": "4n + 1",
        "wrong_answers": '{"4n + 5","n + 4","5n - 1"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 75,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Nth Term Rule]\nStep 1: Find the common difference. The sequence goes up by +4 each time. This means the rule starts with 4n.\nStep 2: The 4 times table is 4, 8, 12, 16. Our sequence is 5, 9, 13, 17.\nStep 3: How do you get from the 4 times table to our sequence? You add 1 to every number.\nFinal rule: 4n + 1."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|perimeter-area",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A rectangle has an area of 48cm² and a width of 6cm. What is its perimeter?",
        "correct_answer": "28cm",
        "wrong_answers": '{"24cm","14cm","32cm"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 90,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Perimeter and Area]\nStep 1: Area = Length × Width. We know 48 = Length × 6.\nStep 2: Divide 48 by 6 to find the length. 48 ÷ 6 = 8cm.\nStep 3: Now we understand the dimensions: a rectangle that is 8cm by 6cm.\nStep 4: Perimeter is the total distance around the outside: 8 + 6 + 8 + 6 = 28cm.\nFinal answer: 28cm."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|measures",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A train travels 120 miles in 2 hours and 30 minutes. What is its average speed in miles per hour (mph)?",
        "correct_answer": "48 mph",
        "wrong_answers": '{"60 mph","50 mph","45 mph"}',
        "marks": 3,
        "difficulty": 3,
        "estimated_time_sec": 120,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Speed, Distance, Time]\nStep 1: Use the DST formula triangle. Speed = Distance ÷ Time.\nStep 2: The distance is 120 miles. The time is 2 hours and 30 minutes. \nStep 3: VERY IMPORTANT: Convert time to a decimal. 30 minutes is 0.5 hours. So, Time = 2.5 hours.\nStep 4: Calculation: 120 ÷ 2.5.\nStep 5: Shortcut: Double both numbers to make it easier. 240 ÷ 5 = 48.\nFinal answer: 48 mph."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|angles",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Two parallel lines are intersected by a transversal. If one angle is 110°, what could be the size of an alternate angle?",
        "correct_answer": "110°",
        "wrong_answers": '{"70°","180°","55°"}',
        "marks": 1,
        "difficulty": 2,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Parallel Lines]\nStep 1: Alternate angles look like a 'Z' shape when drawn on a diagram.\nStep 2: Remember the key parallel line rule: Alternate angles are ALWAYS EQUAL to each other.\nStep 3: Therefore, if the first angle is 110°, the alternate angle is also 110°.\nFinal answer: 110°."
    },
    {
        "track": "11plus",
        "question_type": "Statistics & Data",
        "subtopic": "stats|data-handling",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "The mean of five numbers is 8. Four of the numbers are 5, 9, 7, and 12. What is the fifth number?",
        "correct_answer": "7",
        "wrong_answers": '{"8","10","6"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 90,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Averages]\nStep 1: The 'Mean' is the fair share. If 5 numbers average out to 8, the total sum of all the numbers must be 5 × 8 = 40.\nStep 2: Add up the four numbers you already know: 5 + 9 + 7 + 12 = 33.\nStep 3: Find the missing gap to reach the total sum of 40.\nStep 4: 40 - 33 = 7.\nThe missing fifth number is 7."
    },
    {
        "track": "11plus",
        "question_type": "Statistics & Data",
        "subtopic": "stats|probability",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "I have a bag containing 3 red balls, 5 blue balls, and 2 green balls. What is the probability of picking a blue ball?",
        "correct_answer": "1/2",
        "wrong_answers": '{"5/10","3/10","1/5"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Probability Scale]\nStep 1: Find the total number of items. 3 + 5 + 2 = 10 balls in total.\nStep 2: Find how many represent a 'success' (the blue balls). There are 5 blue balls.\nStep 3: Write as a fraction: 5/10.\nStep 4: Always simplify your answer in probability unless asked otherwise. 5/10 simplifies to 1/2.\nFinal answer: 1/2."
    },
    {
        "track": "11plus",
        "question_type": "Problem Solving & Strategies",
        "subtopic": "strategies|word-problems",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A cinema ticket costs £8.50 for an adult and £4.50 for a child. How much does it cost for 2 adults and 3 children to go to the cinema?",
        "correct_answer": "£30.50",
        "wrong_answers": '{"£28.00","£31.50","£26.50"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 90,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Decoding Word Problems]\nStep 1: Read and Understand. We require the sum of two £8.50 normal tickets and three £4.50 child tickets.\nStep 2: Choose your methods (Multiply then Add). \nStep 3: Solve for adults: 2 × £8.50 = £17.00. \nStep 4: Solve for children: 3 × £4.50. You can do 3 × £4 = £12, 3 × 50p = £1.50, adding to £13.50.\nStep 5: Check your addition: £17.00 + £13.50 = £30.50.\nFinal answer: £30.50."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|coordinates",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A point at (-3, 4) is reflected in the y-axis. What are its new coordinates?",
        "correct_answer": "(3, 4)",
        "wrong_answers": '{"(-3, -4)","(3, -4)","(4, -3)"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Coordinates (The Grid)]\nStep 1: Visualise the 4 Quadrants. The coordinate is currently -3 on the x-axis, and 4 on the y-axis (top left quadrant).\nStep 2: The y-axis is the vertical line going down the middle. This acts as our mirror.\nStep 3: If you reflect across the y-axis, the height (y-coordinate) stays exactly the same: 4.\nStep 4: However, the horizontal position is flipped. The -3 mirrors across the line 0, becoming a positive 3.\nFinal answer: (3, 4)."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|fractions",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Which fraction is NOT equivalent to 3/4?",
        "correct_answer": "16/20",
        "wrong_answers": '{"9/12","15/20","75/100"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Anatomy of a Fraction]\nStep 1: Equivalent fractions are formed by multiplying or dividing both the top and bottom number by the exact same value.\nStep 2: Look at 9/12. (3×3 = 9, 4×3 = 12). Equivalent.\nStep 3: Look at 15/20. (3×5 = 15, 4×5 = 20). Equivalent.\nStep 4: Look at 16/20. (4×5 = 20, but 3×5 is 15, not 16!). This fraction is equal to 4/5, not 3/4."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|2d-3d-shapes",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A regular polygon has an exterior angle of 40°. How many sides does the shape have?",
        "correct_answer": "9 sides",
        "wrong_answers": '{"8 sides","10 sides","12 sides"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 60,
        "image_url": "questions/triangle_exterior_angle.png",
        "image_alt": "",
        "explanation": "[VISUAL: Properties of Shapes]\nStep 1: Remember the primary rule for exterior angles of ANY polygon: all exterior angles add up to 360°.\nStep 2: Since it is a 'regular' polygon, all the exterior angles are the exact same size: 40°.\nStep 3: To find the number of sides, divide the total 360° by the size of one exterior angle.\nStep 4: 360 ÷ 40 = 9.\nFinal answer: 9 sides."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|place-value",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "What is the value of the 7 in the number 3,471,920?",
        "correct_answer": "Seventy thousand",
        "wrong_answers": '{"Seven million","Seven hundred thousand","Seven thousand"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 30,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Architecture of Numbers]\nStep 1: Write down the headers for each column: Millions, Hundred Thousands, Ten Thousands, Thousands, Hundreds, Tens, Units.\nStep 2: Look at the number 3,471,920 from right to left.\nStep 3: The 0 is Units, 2 is Tens, 9 is Hundreds, 1 is Thousands, and 7 is Ten Thousands.\nStep 4: The 7 means 7 Ten Thousands, which is exactly 70,000.\nFinal answer: Seventy thousand."
    },
    {
        "track": "11plus",
        "question_type": "Statistics & Data",
        "subtopic": "stats|charts-graphs",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "In a pie chart, if the 'Blue' section has an angle of 90°, what fraction of the whole does it represent?",
        "correct_answer": "1/4",
        "wrong_answers": '{"1/3","1/2","1/10"}',
        "marks": 1,
        "difficulty": 2,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "Step 1: A full pie chart operates in a complete circle, which is always 360°.\nStep 2: The Blue section takes up 90° out of the total 360°.\nStep 3: Write this out as a fraction: 90/360.\nStep 4: Simplify the fraction by dividing top and bottom by 90.\nStep 5: 90 ÷ 90 = 1, and 360 ÷ 90 = 4. The resulting fraction is 1/4.\nFinal answer: 1/4."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|sequences",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "What is the next number in this sequence? 2, 5, 10, 17, 26, ...",
        "correct_answer": "37",
        "wrong_answers": '{"35","39","40"}',
        "marks": 2,
        "difficulty": 3,
        "estimated_time_sec": 75,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Nth Term Rule]\nStep 1: Look at the differences between the numbers.\nStep 2: 5 - 2 = 3. 10 - 5 = 5. 17 - 10 = 7. 26 - 17 = 9.\nStep 3: The differences themselves are a sequence! They go up in odd numbers (+3, +5, +7, +9).\nStep 4: This means the next difference must be +11.\nStep 5: 26 + 11 = 37.\nFinal answer: 37."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|fractions",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "What is 2/5 + 1/3?",
        "correct_answer": "11/15",
        "wrong_answers": '{"3/8","2/15","3/15"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Anatomy of a Fraction]\nStep 1: You cannot add fractions with different denominators (bottom numbers).\nStep 2: Find a common multiple for 5 and 3. The Lowest Common Multiple is 15.\nStep 3: Convert 2/5 to 15ths. Multiply top and bottom by 3 to get 6/15.\nStep 4: Convert 1/3 to 15ths. Multiply top and bottom by 5 to get 5/15.\nStep 5: Add them up: 6/15 + 5/15 = 11/15.\nFinal answer: 11/15."
    },
    {
        "track": "11plus",
        "question_type": "Number & Arithmetic",
        "subtopic": "number|fractions",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Multiply 3/4 by 2/3.",
        "correct_answer": "1/2",
        "wrong_answers": '{"6/12","5/7","1/4"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Anatomy of a Fraction]\nStep 1: The wonderful rule for multiplying fractions is that we just multiply straight across!\nStep 2: Multiply the numerators (tops): 3 × 2 = 6.\nStep 3: Multiply the denominators (bottoms): 4 × 3 = 12.\nStep 4: The answer is 6/12.\nStep 5: Always simplify your fractions! 6 divides evenly into 12. 6/12 simplifies to 1/2.\nFinal answer: 1/2."
    },
    {
        "track": "11plus",
        "question_type": "Algebra & Ratio",
        "subtopic": "algebra|proportion",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "If 4 apples cost £1.20, how much will 7 apples cost?",
        "correct_answer": "£2.10",
        "wrong_answers": '{"£2.40","£1.80","£2.00"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "Step 1: We must find the standard value first! What is the cost of ONE apple? \nStep 2: £1.20 ÷ 4 = £0.30 (or 30p).\nStep 3: Now that we know each apple costs 30p, we just multiply by the amount we need: 7.\nStep 4: 7 × £0.30 = £2.10.\nFinal answer: £2.10."
    },
    {
        "track": "11plus",
        "question_type": "Geometry & Measures",
        "subtopic": "geometry|volume-surface-area",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "A cuboid has a length of 5cm, a width of 3cm and a height of 4cm. What is its volume?",
        "correct_answer": "60cm³",
        "wrong_answers": '{"12cm³","24cm³","47cm³"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 60,
        "image_url": "",
        "image_alt": "",
        "explanation": "Step 1: The formula for the Volume of a cuboid is simply Length × Width × Height.\nStep 2: Look at our dimensions: 5cm, 3cm, and 4cm.\nStep 3: Multiply them together. 5 × 3 = 15.\nStep 4: Multiply by height. 15 × 4 = 60.\nStep 5: Ensure your answer uses the correct volume unit: cm cubed (cm³).\nFinal answer: 60cm³."
    },
    {
        "track": "11plus",
        "question_type": "Problem Solving & Strategies",
        "subtopic": "strategies|logic",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "Tom thinks of a number. He doubles it, adds 5, and gets 21. What number did he think of?",
        "correct_answer": "8",
        "wrong_answers": '{"16","13","9"}',
        "marks": 2,
        "difficulty": 2,
        "estimated_time_sec": 75,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: Function Machine]\nStep 1: If Tom ends up at 21, let's reverse the machine and work backwards using inverse operations!\nStep 2: The last thing Tom did was 'add 5'. We must subtract 5. 21 - 5 = 16.\nStep 3: Before that, Tom 'doubled it' (multiplied by 2). We must divide by 2. \nStep 4: 16 ÷ 2 = 8.\nFinal answer: 8."
    },
    {
        "track": "11plus",
        "question_type": "Statistics & Data",
        "subtopic": "stats|data-handling",
        "tier": "11+ Standard",
        "calculator": "Non-Calculator",
        "question": "What is the median of these numbers: 14, 2, 7, 21, 6?",
        "correct_answer": "7",
        "wrong_answers": '{"10","21","6"}',
        "marks": 1,
        "difficulty": 1,
        "estimated_time_sec": 45,
        "image_url": "",
        "image_alt": "",
        "explanation": "[VISUAL: The 3 M's]\nStep 1: 'Median' sounds like 'Medium' or 'Middle'.\nStep 2: First, you must write the numbers in order from smallest to largest.\nStep 3: Reordered list: 2, 6, 7, 14, 21.\nStep 4: Take the number directly in the middle of the list.\nFinal answer: 7."
    }
]

with open('supabase/data/generated/11plus_premium_question_bank.csv', mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["id","question_type","tier","calculator","track","subtopic","question","correct_answer","wrong_answers","marks","difficulty","estimated_time_sec","image_url","image_alt","explanation"])
    writer.writeheader()
    for q in questions:
        writer.writerow(q)
