#!/usr/bin/env bash
# Push local .env values into Supabase Edge Function secrets.
# This does not print secret values.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo "Missing .env" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

set_secret() {
  local name="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "Skip $name (empty)" >&2
    return
  fi
  echo "Setting $name"
  supabase secrets set "${name}=${value}"
}

set_secret SUPABASE_URL "${SUPABASE_URL:-${VITE_SUPABASE_URL:-}}"
set_secret SUPABASE_ANON_KEY "${SUPABASE_ANON_KEY:-${VITE_SUPABASE_PUBLISHABLE_KEY:-${VITE_SUPABASE_ANON_KEY:-}}}"
set_secret SUPABASE_SERVICE_ROLE_KEY "${SUPABASE_SERVICE_ROLE_KEY:-}"

set_secret ENVIRONMENT "${ENVIRONMENT:-}"
set_secret APP_BASE_URL "${APP_BASE_URL:-}"
set_secret OPENAI_API_KEY "${OPENAI_API_KEY:-}"
set_secret GEMINI_API_KEY "${GEMINI_API_KEY:-}"
set_secret RESEND_API_KEY "${RESEND_API_KEY:-}"
set_secret SUPPORT_EMAIL_FROM "${SUPPORT_EMAIL_FROM:-}"
set_secret GOOGLE_CLIENT_ID "${GOOGLE_CLIENT_ID:-${VITE_GOOGLE_CLIENT_ID:-}}"
set_secret VITE_AI_FEATURE_ENABLED "${VITE_AI_FEATURE_ENABLED:-}"

stripe_vars=(
  STRIPE_SECRET_KEY
  STRIPE_SECRET_KEY_TEST
  STRIPE_SECRET_KEY_LIVE
  STRIPE_WEBHOOK_SECRET
  STRIPE_WEBHOOK_SECRET_TEST
  STRIPE_WEBHOOK_SECRET_LIVE
  STRIPE_PRICE_MONTHLY
  STRIPE_PRICE_MONTHLY_TEST
  STRIPE_PRICE_MONTHLY_LIVE
  STRIPE_PRICE_ANNUAL
  STRIPE_PRICE_ANNUAL_TEST
  STRIPE_PRICE_ANNUAL_LIVE
  STRIPE_PRICE_11PLUS_MONTHLY
  STRIPE_PRICE_11PLUS_MONTHLY_TEST
  STRIPE_PRICE_11PLUS_MONTHLY_LIVE
  STRIPE_PRICE_11PLUS_WEEKLY
  STRIPE_PRICE_11PLUS_WEEKLY_TEST
  STRIPE_PRICE_11PLUS_WEEKLY_LIVE
  STRIPE_PRICE_11PLUS_ANNUAL
  STRIPE_PRICE_11PLUS_ANNUAL_TEST
  STRIPE_PRICE_11PLUS_ANNUAL_LIVE
  STRIPE_PRICE_11PLUS_ULTRA_MONTHLY
  STRIPE_PRICE_11PLUS_ULTRA_MONTHLY_TEST
  STRIPE_PRICE_11PLUS_ULTRA_MONTHLY_LIVE
  STRIPE_PRICE_11PLUS_ULTRA_ANNUAL
  STRIPE_PRICE_11PLUS_ULTRA_ANNUAL_TEST
  STRIPE_PRICE_11PLUS_ULTRA_ANNUAL_LIVE
  STRIPE_PRICE_ELEVEN_PLUS_MONTHLY
  STRIPE_PRICE_ELEVEN_PLUS_MONTHLY_TEST
  STRIPE_PRICE_ELEVEN_PLUS_MONTHLY_LIVE
  STRIPE_PRICE_ELEVEN_PLUS_ANNUAL
  STRIPE_PRICE_ELEVEN_PLUS_ANNUAL_TEST
  STRIPE_PRICE_ELEVEN_PLUS_ANNUAL_LIVE
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_MONTHLY
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_MONTHLY_TEST
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_MONTHLY_LIVE
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_ANNUAL
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_ANNUAL_TEST
  STRIPE_PRICE_ELEVEN_PLUS_ULTRA_ANNUAL_LIVE
)

for name in "${stripe_vars[@]}"; do
  set_secret "$name" "${!name:-}"
done

echo "Done. Redeploy any Edge Functions whose secrets changed."
