-- Auto-generated by scripts/audit-fix-11plus-question-bank.mjs
-- Scope: 11+ question rendering + answer integrity fixes.

BEGIN;

UPDATE public.exam_questions
SET wrong_answers = ARRAY['25', '15m/s', '30m/s', '900m/s']::text[]
WHERE id = '4fc31afc-523c-4ed6-85c4-4bca606731d8';
UPDATE public.exam_questions
SET wrong_answers = ARRAY['25', '30km/h', '20km/h', '60km/h']::text[]
WHERE id = 'bbefd940-32d9-4198-84bc-e4197a15fce0';
UPDATE public.extreme_questions
SET explanation = 'Step 1 (Trial and error / Estimation): We need $n (n+1) (n+2) = 120$.
Step 2 (Testing values): Try 3 x 4 x 5 = 60 (too low). Try 4 x 5 x 6 = 120 (perfect).
Step 3 (Calculating the sum): 4 + 5 + 6 = 15.
Final answer: 15'
WHERE id = '958861ac-9a2b-4a7d-bb47-f42ca0415c44';
UPDATE public.extreme_questions
SET wrong_answers = ARRAY['36cm²', '25cm²', '64cm²', '100cm²']::text[]
WHERE id = '72282de2-d68c-4baa-86ad-a5dd3d467d55';
UPDATE public.extreme_questions
SET wrong_answers = ARRAY['5', '0', '15', '11']::text[],
    all_answers = ARRAY['10', '5', '0', '15', '11']::text[]
WHERE id = '5e6a708f-b474-4605-9458-1229533f9282';

COMMIT;
